### ISSUE TITLE
world gen is not happening version 1.19.2

### ISSUE THREAD

**Issue by kiritoreaper** [DenisMasterHerobrine/MagicalForest#14]
I get this error every time i try to create a world. I will wait 1 hour and no progress is done on the world gen so i end up stopping the the task and this is the error i find in the log before the world gen stops.

com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

i have a bunch of biome mods so i cant tell where the issues is occuring exactly. but i am using cyanide for better world gen info

this is everthing world gen related:

at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141) ~[cyanide-forge-1.19.2-3.0.1.jar%23560!/:3.0.1]
	at net.minecraft.world.level.biome.FeatureSorter.handler$dni000$buildFeaturesPerStepWithAdvancedCycleDetection(FeatureSorter.java:529) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$3(ModdedBiomeSlicesManager.java:108) ~[blueprint-1.19.2-6.2.0.jar%23504!/:6.2.0]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:397) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23126!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23777!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

here are the biome mode that im aware of (might have some mods that add biomes that im unaware of):
deep aether
the aether redux
autuminity
alex cave
alex mobs
amplified nether
ars nouveau
atmospheric
born in chaos
deeper and darker
ecologics
enviromental
evil craft
garden of the dead
nullscape
nyctophobia
tectonic
the aether
the abyss 2
the graveyard
twilight forest
the undergarden
tropicraft
voidscape

**Comment by kiritoreaper** [comment]
sorry there is no alex cave

**Comment by DenisMasterHerobrine** [comment]
Currently this mod is in semi-abandoned state. Still, this issue currently doesn't help me to find out, what the real cause it except the feature cycle issue being referenced. (you may find similar issues there)

Please, provide a full log, so I could find the real cause of the issue and where the problem was, so I could fix it, when I get back to Magical Forest.

**Comment by kiritoreaper** [comment]
[log.txt](https://github.com/DenisMasterHerobrine/MagicalForest/files/13689634/log.txt)

here you go

**Comment by DenisMasterHerobrine** [comment]
Seems this is related to `'gothic:meadow_knotweed_gen'` feature from the Gothic mod, you could try to find out if this mod is causing the issue instead of Magical Forest.

**Comment by kiritoreaper** [comment]
its seems to be gothic rpg and wizardy delight that causes the issue
both mods cause the issue without needing the other
